//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNTN_prov.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PNTN_prov.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_6_1 {
            get {
                object obj = ResourceManager.GetObject("4_6_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_6_2 {
            get {
                object obj = ResourceManager.GetObject("4_6_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_6_3 {
            get {
                object obj = ResourceManager.GetObject("4_6_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_6_4 {
            get {
                object obj = ResourceManager.GetObject("4_6_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_6_5 {
            get {
                object obj = ResourceManager.GetObject("4_6_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_6_6 {
            get {
                object obj = ResourceManager.GetObject("4_6_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на δ X1:1-X1:2.
        /// </summary>
        internal static string accuracy__X1_1_X1_2 {
            get {
                return ResourceManager.GetString("accuracy_ X1:1-X1:2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на δ X1:5-X1:6.
        /// </summary>
        internal static string accuracy_X1_5_X1_6 {
            get {
                return ResourceManager.GetString("accuracy_X1:5-X1:6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на δ X2:1-X2:2.
        /// </summary>
        internal static string accuracy_X2_1_X2_2 {
            get {
                return ResourceManager.GetString("accuracy_X2:1-X2:2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на δ X2:3-X2:6.
        /// </summary>
        internal static string accuracy_X2_3_X2_6 {
            get {
                return ResourceManager.GetString("accuracy_X2:3-X2:6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на δ X2:4-X2:5.
        /// </summary>
        internal static string accuracy_X2_4_X2_5 {
            get {
                return ResourceManager.GetString("accuracy_X2:4-X2:5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на δ X2:7-X2:8.
        /// </summary>
        internal static string accuracy_X2_7_X2_8 {
            get {
                return ResourceManager.GetString("accuracy_X2:7-X2:8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pntn_const.txt.
        /// </summary>
        internal static string ConstantsFile {
            get {
                return ResourceManager.GetString("ConstantsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I X2:4-X2:5.
        /// </summary>
        internal static string current_X2_4_X2_5 {
            get {
                return ResourceManager.GetString("current_X2:4-X2:5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I X2:7-X2:8.
        /// </summary>
        internal static string current_X2_7_X2_8 {
            get {
                return ResourceManager.GetString("current_X2:7-X2:8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не исправен.
        /// </summary>
        internal static string DefaultLabelsTextFaulty {
            get {
                return ResourceManager.GetString("DefaultLabelsTextFaulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исправен.
        /// </summary>
        internal static string DefaultLabelsTextСorrect {
            get {
                return ResourceManager.GetString("DefaultLabelsTextСorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pntn_protokol.txt.
        /// </summary>
        internal static string ProtokolFile {
            get {
                return ResourceManager.GetString("ProtokolFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap общая_схема {
            get {
                object obj = ResourceManager.GetObject("общая_схема", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
